# Generated by Django 3.1 on 2020-08-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200813_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='caption',
        ),
    ]
