# Generated by Django 3.1 on 2020-08-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
