# Generated by Django 3.1 on 2020-09-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
