# Generated by Django 3.1 on 2020-09-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0003_auto_20200906_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Post'),
        ),
    ]
